// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductApi.Infrastructure.Data;

#nullable disable

namespace ProductApi.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250827153502_AddUniqueConstraintToProductName")]
    partial class AddUniqueConstraintToProductName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductApi.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 123456,
                            AvailableStock = 120,
                            Category = "Eyewear",
                            CreatedAt = new DateTime(2025, 8, 27, 15, 35, 1, 957, DateTimeKind.Utc).AddTicks(9250),
                            Name = "VisionPro Eyeglass Lens",
                            Price = 149.99m
                        },
                        new
                        {
                            ProductId = 123457,
                            AvailableStock = 200,
                            Category = "Eyewear",
                            CreatedAt = new DateTime(2025, 8, 27, 15, 35, 1, 957, DateTimeKind.Utc).AddTicks(9250),
                            Name = "BlueLight Blocking Glasses",
                            Price = 89.50m
                        },
                        new
                        {
                            ProductId = 123458,
                            AvailableStock = 15,
                            Category = "Medical",
                            CreatedAt = new DateTime(2025, 8, 27, 15, 35, 1, 957, DateTimeKind.Utc).AddTicks(9250),
                            Name = "Precision Microscope X200",
                            Price = 5499.00m
                        },
                        new
                        {
                            ProductId = 123459,
                            AvailableStock = 25,
                            Category = "Medical",
                            CreatedAt = new DateTime(2025, 8, 27, 15, 35, 1, 957, DateTimeKind.Utc).AddTicks(9250),
                            Name = "Portable Diagnostic Kit",
                            Price = 1299.00m
                        },
                        new
                        {
                            ProductId = 123460,
                            AvailableStock = 40,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 8, 27, 15, 35, 1, 957, DateTimeKind.Utc).AddTicks(9250),
                            Name = "CinePrime 50mm Camera Lens",
                            Price = 899.50m
                        },
                        new
                        {
                            ProductId = 123461,
                            AvailableStock = 12,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 8, 27, 15, 35, 1, 957, DateTimeKind.Utc).AddTicks(9250),
                            Name = "Compact Projector StarView",
                            Price = 799.00m
                        },
                        new
                        {
                            ProductId = 123462,
                            AvailableStock = 60,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 8, 27, 15, 35, 1, 957, DateTimeKind.Utc).AddTicks(9260),
                            Name = "VR Headset VisionX",
                            Price = 499.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
